<template>
      <section>
                <div id="app" slot="content">
                              <main class="main-content">
                                              <el-form :model="View.queryParams" ref="waveSoList" :rules="rules">
                                                                    <el-row>
                                                                                              <InputWidget :span="5" label="发运单号" prop="soNo" v-model.trim="View.queryParams.soNo"></InputWidget>
                                                                                                                      <EnumSelectWidget label="类型" prop="soType" enumKey="soType" v-model.trim="View.queryParams.soType"></EnumSelectWidget>
                                                                                                                                              <MultiSelectWidget :span="6" prop="soStatus" label="状态" enumKey="soStatusV3" v-model.trim="View.queryParams.soStatus"></MultiSelectWidget>
                                                                                                                                                                      <InputWidget label="线路" prop="routeCode" v-model.trim="View.queryParams.routeCode"></InputWidget>
                                                                                                                                                                                              <ArrowWidget :value="View.arrowUp" @change="View.arrowUp = !View.arrowUp"></ArrowWidget>
                                                                                                                                                                                                                  </el-row>

                                                                                                                                                                                                                                      <el-row v-show="View.arrowUp">
                                                                                                                                                                                                                                                                <InputWidget label="客户" prop="customerCode" v-model.trim="View.queryParams.customerCode"></InputWidget>
                                                                                                                                                                                                                                                                                        <InputWidget label="客户名称" prop="customerName" v-model.trim="View.queryParams.customerName"></InputWidget>
                                                                                                                                                                                                                                                                                                                <InputWidget label="货主" prop="ownerCode" v-model.trim="View.queryParams.ownerCode"></InputWidget>
                                                                                                                                                                                                                                                                                                                                        <InputWidget label="波次号" prop="waveCode" v-model.trim="View.queryParams.waveCode"></InputWidget>
                                                                                                                                                                                                                                                                                                                                                            </el-row>

                                                                                                                                                                                                                                                                                                                                                                                <el-row v-show="View.arrowUp">
                                                                                                                                                                                                                                                                                                                                                                                                          <DateWidget label="要求发运时间" :labelWidth="100"
                                                                                                                                                                                                                                                                                                                                                                                                                                                          propFrom="sendTimeStart"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              propTo="sendTimeEnd"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  :timeFrom="View.queryParams.sendTimeStart"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  :timeTo="View.queryParams.sendTimeEnd"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  :keyArr="[1, 3, 0]"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  @change="emitCallback2"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ></DateWidget>

                                                                                                                                                                                                                                                                                                                                                                                                                                  <DateWidget label="生单时间" :labelWidth="100"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  propFrom="createTimeStart"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      propTo="createTimeEnd"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          :timeFrom="View.queryParams.createTimeStart"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          :timeTo="View.queryParams.createTimeEnd"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          @change="emitCallback"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ></DateWidget>
                                                                                                                                                                                                                                                                                                                                                                                                                                                      </el-row>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <el-row>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <el-col :span="24">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <el-button :loading="View.loading" @click="submitForm('waveSoList')" type="primary" size="small">查询</el-button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <el-button @click="emptyFilterValue('waveSoList')" type="warning" size="small">清空</el-button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <el-button v-auth="PERMISSION.GENERATE" :loading="View.loading" @click="switchOperate(1)" type="primary" size="small">生成波次</el-button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <el-button v-auth="PERMISSION.JOIN" :loading="View.loading" @click="switchOperate(2)" type="primary" size="small">加入波次</el-button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <el-button v-auth="PERMISSION.BATCH_GENERATE" :loading="View.loading" @click="createWaveBatch()" type="primary" size="small">一键生成波次</el-button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </el-col>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </el-row>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </el-form>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <el-table slot="table" :data="View.resultList" stripe border class="adjust-font"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ref="multipleTable"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            @select="handleOneChange"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            @select-all="handleAllChange">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <el-table-column type="selection" width="55"></el-table-column>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <el-table-column label="序号" type="index" width="60"></el-table-column>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <el-table-column label="发运单号" prop="soNo" width="133"></el-table-column>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <el-table-column label="类型" prop="soTypeDesc" min-width="113"></el-table-column>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <el-table-column label="状态" prop="soStatusDesc" min-width="75"></el-table-column>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <el-table-column label="客户" prop="customerCode" min-width="120"></el-table-column>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <el-table-column label="客户名称" prop="customerName" width="100"></el-table-column>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <el-table-column label="波次号" width="100">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <template slot-scope="scope">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span>{{scope.row.waveCode || '-'}}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </template>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </el-table-column>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <el-table-column label="货主" prop="ownerCode" min-width="100"></el-table-column>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <el-table-column label="要求发运时间" prop="sendTime" min-width="145"></el-table-column>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <el-table-column label="线路" prop="routeCode" min-width="150"></el-table-column>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <el-table-column label="线路序号" prop="routeSequence" min-width="65"></el-table-column>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <el-table-column la></el-table-column>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <el-table-column label="操作" min-width="60" fixed="right">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ible" class="wave-dialog">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <el-form :model="View.waveParams" ref="waveFilter">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <el" type="primary" size="small">查询</el-button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <el-button :loading="View.loading" @click="waolumn>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <el-table-column prop="totalCount" label="触点数" min-width="80"></el-table-column>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <el-table-column prop="totalDetailCount" label=               </div>
                                </el-dialog>
                                            </main>
                                                    </div>

                                                        </section>
</template>

<script>
   sendTimeStart: '',
                   sendTimeEnd: '',
                                   createTimeStart: '',
                                                   createTimeEnd: '',
                                                                   waveCode: ''
                                                                               };
            const View = {
                              currentPage: 1,
                                              pageSize: Number(localStorage.getItem('pageSize') || '50') || 50,
                                                                   this.View.loading = false;
                                                      this.View.waveCount = 0;
                                                                              this.View.gridData = [];

                                                                                                      this.$alert(err.msg || '服务器错误!', '提示', {confirmButtonText: '确定', type: 'error'});
                                                                                                                          });
            },
                        /**
                                       * 选择操作
                                                    */
                        switchOperate(n) {
                                          const multipleSelection = thi
                                                            }

                const params = {
                            ror'});
                                                });
            },
                        /**
                                       * 生成波次
                                                    */
                        createWave(soIds) {
                                          if (this.View.loading) {
                                                                return;
                                                                                }

                                                          const catData = {
                                                                                ...this.catData,
                                                                                                    msg: 'CreateWave',
                                                                                                                    };

                                                                          this.View.loading = true;
                                                                                          CreateWave(soIds, catData)
                                                                                                                .then((res) => {
                                                                                                                                          this.View.loading = false;
                                                                                                                                                                  this.query();

                                                                                                                                                                                          return res;
                                                                                                                                                                                                              })
                                                                                                              .then((waveCode) => {
                                                                                                                                        this.jumpToWaveList(waveCode);
                                                                                                                                                            })
                                                                                                                                  .catch(err => {
                                                                                                                                                            this.View.loading = false;
                                                                                                                                                                                    this.$alert(err.msg || '服务器错误', '提示', {confirmButtonText: '确定', type: 'error'});
                                                                                                                                                                                                        });
                                                                                                                                              },
                                                                                                                                                          /**
                                                                                                                                                                         * 一键生成波次
                                                                                                                                                                                      */
                                                                                                                                                          createWaveBatch() {
                                                                                                                                                                            if (this.View.loading) {
                                                                                                                                                                                                  return;
                                                                                                                                                                                                                  }

                                                                                                                                                                                            const catData = {
                                                                                                                                                                                                                  ...this.catData,
                                                                                                                                                                                                                                      msg: 'CreateWaveBatch',
                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                            this.View.loading = true;
                                                                                                                                                                                                                            CreateWaveBatch({}, catData)
                                                                                                                                                                                                                                                  .then((res) => {
                                                                                                                                                                                                                                                                            this.View.loading = false;
                                                                                                                                                                                                                                                                                                    this.query();
                                                                                                                                                                                                                                                                                                                            return res;
                                                                                                                                                                                                                                                                                                                                                })
                                                                                                                                                                                                                                                .then((count) => {
                                                                                                                                                                                                                                                                          this.$confirm('成功生成了' + count + '个波次, 是否跳转至波次列表?', '提示', {
                                                                                                                                                                                                                                                                                                        confirmButtonText: '确定',
                                                                                                                                                                                                                                                                                                                                    cancelButtonText: '取消',
                                                                                                                                                                                                                                                                                                                                                                type: 'success'
                                                                                                                                                                                                                                                                                                                                                                                          }).then(() => {
                                                                                                                                                                                                                                                                                                        // this.jumpToWaveList();
                                                                                                                                                                                                                                                                                                        this.Open('/app/newoub/waveList/');
                                                                                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                                                                                               });
                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                  handleSizeChange(val) {
                                                                                                                                                                                                                                                                                                                    this.View.pageSize = val;
                                                                                                                                                                                                                                                                                                                                    localStorage.setItem('pageSize', val);
                                                                                                                                                                                                                                                                                                                                                    this.View.currentPage = 1;
                                                                                                                                                                                                                                                                                                                                                                    this.query();
                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                            handleCurrentChange(page) {
                                                                                                                                                                                                                                                                                                                                                                                                              this.View.currentPage = page;
                                                                                                                                                                                                                                                                                                                                                                                                                              this.query();
                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                      handleWaveSizeChange(val) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        this.View.currentWavePage = val;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        localStorage.setItem('pageSize', val);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        this.View.currentWavePage = 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        this.waveQuery();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                handleWaveCurrentChange(page) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  this.View.currentWavePage = page;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  this.waveQuery();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
</script>

<style lang="less">
.wave-dialog .el-dialog {
      width: 70%;
}

                        .wave-dialog .el-dialog__body {
                              padding: 10px 20px;
                        }

                        .el-dialog__wrapper.wave-dialog {
                              height: 90vh;
                        }
</style>

